# Basic
title: Zen Space
subtitle: Sharing opinions and funny things.
welcome_message: Welcome to my house!
description: Gundam is men's romance | Core Gamer | Individual Sports Fan | Han Shot First | ShanghaiTech Undergraduate | Computer Science
creator: <a href="https://github.com/khaoszen">@KhaosZen</a>

url: "http://khaoszen.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog/我的博文
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Main Page/主页, description: Main, url: 'index.html'}
    - {title: Others/其它, description: Others, url: 'theuglyduckling.html'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: khaoszen
    
# Social
social:
    weibo: Khaos_Zen
    github: KhaosZen
    twitter: ZodiacXCyborg
    mail: khaoszen@163.com

